### ISSUE TITLE
探针IP加到CF拦截白名单

### ISSUE THREAD

**Issue by lostbytez** [yumusb/nezha-new#2]
请问这一步具体怎么做？目前报403 you are blocked by nezha WAF 谢谢

**Comment by yumusb** [comment]
你说的这个 配置一下 真实IP请求头 即可。

**Comment by CosmosLibra** [comment]
![image](https://github.com/user-attachments/assets/953c2880-6075-41da-a71d-bef265ebaa26)
![image](https://github.com/user-attachments/assets/9918e01d-b8a3-402b-b1d0-8735b1aa7ffd)
这么设置了还是被拦截了

**Comment by yumusb** [comment]
你好好看看 我说的是什么

**Comment by lostbytez** [comment]
/dashboard/settings  里面的真实请求头 配置的是CF-Connecting-IP 点击保存 立马就报403错误了

**Comment by lostbytez** [comment]
已解决

**Comment by mkblbj** [comment]
> 已解决

麻烦问下怎么解决的，我这边经常抱502，时而可以访问时而502
